# Generated by Django 3.0.4 on 2020-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='rest_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
