# Generated by Django 3.0.4 on 2020-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200310_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='rest_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
