# Generated by Django 3.0.4 on 2020-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200311_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rest',
            field=models.CharField(default='m', max_length=20),
        ),
    ]
