# Generated by Django 3.0.4 on 2020-03-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200311_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cust_id',
            new_name='cust',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='food_id',
            new_name='food',
        ),
    ]
